# This example demonstrates the ability to pass artifacts
# from one step to the next.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: selbat-pipeline
  templates:
  - name: selbat-pipeline
    steps:
    - - name: pre-processing
        template: pre-processing
    - - name: lookup
        template: lookup
        arguments:
          artifacts:
          - name: file
            from: "{{steps.pre-processing.outputs.artifacts.output}}"   
    - - name: features-extraction
        template: features-extraction
        arguments:
          artifacts:
          - name: file
            from: "{{steps.lookup.outputs.artifacts.output}}"
    - - name: prediction
        template: prediction
        arguments:
          artifacts:
          - name: file
            from: "{{steps.features-extraction.outputs.artifacts.output}}"
    - - name: features-extraction-revision
        template: features-extraction-revision
        arguments:
          artifacts:
          - name: file
            from: "{{steps.prediction.outputs.artifacts.output}}"
    - - name: prediction2
        template: prediction2
        arguments:
          artifacts:
          - name: file
            from: "{{steps.features-extraction-revision.outputs.artifacts.output}}"
    - - name: export
        template: export
        arguments:
          artifacts:
          - name: file
            from: "{{steps.prediction2.outputs.artifacts.output}}"                                        
    
  - name: pre-processing
    container:
      image: roby944/data_preparation:latest
      command: [sh, -c]
      args: ["python data_preparation.py film.csv wikidata"]
    outputs:
      artifacts:
      - name: output
        path: /tmp/output.json

  - name: lookup
    inputs:
      artifacts:
      - name: file
        path: /tmp/file
    container:
      image: roby944/lookup:latest
      command: [sh, -c]
      args: ["python lookup.py /tmp/file"]
    outputs:
      artifacts:
      - name: output
        path: /tmp/output.json 

  - name: features-extraction
    inputs:
      artifacts:
      - name: file
        path: /tmp/file
    container:
      image: roby944/features_extraction:latest
      command: [sh, -c]
      args: ["python features_extraction.py /tmp/file"]
    outputs:
      artifacts:
      - name: output
        path: /tmp/output.json 

  - name: prediction
    inputs:
      artifacts:
      - name: file
        path: /tmp/file
    container:
      image: roby944/prediction:latest
      command: [sh, -c]
      args: ["python prediction.py /tmp/file rho"]
    outputs:
      artifacts:
      - name: output
        path: /tmp/output.json  
  
  - name: features-extraction-revision
    inputs:
      artifacts:
      - name: file
        path: /tmp/file
    container:
      image: roby944/features_extraction_revision:latest
      command: [sh, -c]
      args: ["python features_extraction_revision.py /tmp/file"]
    outputs:
      artifacts:
      - name: output
        path: /tmp/output.json

  - name: prediction2
    inputs:
      artifacts:
      - name: file
        path: /tmp/file
    container:
      image: roby944/prediction:latest
      command: [sh, -c]
      args: ["python prediction.py /tmp/file rho2"]
    outputs:
      artifacts:
      - name: output
        path: /tmp/output.json

  - name: export
    inputs:
      artifacts:
      - name: file
        path: /tmp/file
    container:
      image: roby944/export:latest
      command: [sh, -c]
      args: ["python export.py /tmp/file"]
    outputs:
      artifacts:
      - name: output
        path: /tmp/output.json
