version: "3"

services:
   jupyter:
    image: cremarco/mantis-jupyter
    container_name: selbat_jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      RESTARTABLE: "yes"
    env_file:
      - ./.env  
    ports:
      - "${JUPYTER_PORT}:8888"
    restart: always  
    volumes:
      - ./work:/home/jovyan/work
    