version: "3"

services:
   jupyter:
    image: roby944/jupyter
    container_name: alligator_scalabe_jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      RESTARTABLE: "yes"
    env_file:
      - ./.env  
    ports:
      - "${MY_JUPYTER_PORT}:8888"
    restart: always  
    volumes:
      - ./work:/home/jovyan/work
    
